/*
 * PORT_Config.h
 *
 *  Created on: 10-04-2024
 *   Author: Marwan Aboulfath
 *
 */
#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_


/************* PINS Direction   *********************/




/* Set pin direction
 * Options:
 * 1. DIO_INPUT
 * 2. DIO_OUTPUT
 */
#define DIO_INPUT 				    0
#define DIO_OUTPUT 					1

/*PORTA DIRECTION*/
#define PORTA_PIN0_DIR				DIO_OUTPUT		// LED Pins
#define PORTA_PIN1_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN2_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN3_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN4_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN5_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN6_DIR				DIO_OUTPUT      // LED Pins
#define PORTA_PIN7_DIR				DIO_OUTPUT      // LED Pins

/*PORTB DIRECTION*/
#define PORTB_PIN0_DIR				DIO_OUTPUT		// ALARM pin
#define PORTB_PIN1_DIR				DIO_INPUT		// ALARM STOP pin
#define PORTB_PIN2_DIR				DIO_INPUT		// HOUSE EXIT pin
#define PORTB_PIN3_DIR				DIO_OUTPUT		// FAN 1 Pin
#define PORTB_PIN4_DIR				DIO_OUTPUT		// SLAVE SELECT pin
#define PORTB_PIN5_DIR				DIO_OUTPUT		// MOSI pin
#define PORTB_PIN6_DIR				DIO_INPUT		// MISO pin
#define PORTB_PIN7_DIR				DIO_OUTPUT		// SCK pin

/*PORTC DIRECTION*/
#define PORTC_PIN0_DIR				DIO_OUTPUT		// LCD DATA PIN 0
#define PORTC_PIN1_DIR				DIO_OUTPUT      // LCD DATA PIN 1
#define PORTC_PIN2_DIR				DIO_OUTPUT      // LCD DATA PIN 2
#define PORTC_PIN3_DIR				DIO_OUTPUT      // LCD DATA PIN 3
#define PORTC_PIN4_DIR				DIO_OUTPUT      // LCD DATA PIN 4
#define PORTC_PIN5_DIR				DIO_OUTPUT      // LCD DATA PIN 5
#define PORTC_PIN6_DIR				DIO_OUTPUT      // LCD DATA PIN 6
#define PORTC_PIN7_DIR				DIO_OUTPUT      // LCD DATA PIN 7

/*PORTD DIRECTION*/
#define PORTD_PIN0_DIR				DIO_INPUT		// RX RECIEVE pin
#define PORTD_PIN1_DIR				DIO_OUTPUT		// TX TRANSMIT pin
#define PORTD_PIN2_DIR				DIO_INPUT		// ROOM1 BUTTON pin
#define PORTD_PIN3_DIR				DIO_INPUT		// ROOM2 BUTTON pin
#define PORTD_PIN4_DIR				DIO_OUTPUT		// LCD RS pin
#define PORTD_PIN5_DIR				DIO_OUTPUT		// LCD RW pin
#define PORTD_PIN6_DIR				DIO_OUTPUT		// LCD E pin
#define PORTD_PIN7_DIR				DIO_OUTPUT		// FAN 2 pin


/****************** PINS Values   *******************/
/*INPUT Values*/
#define INPUT_FLOATING			    0
#define INPUT_PULLUP  			    1


/* OUTPUT Values  */
#define OUTPUT_LOW   			    0
#define OUTPUT_HIGH   			 	1

/*  $ Choose:-
			1- INPUT_FLOATING
			2- INPUT_PULLUP
			3- OUTPUT_LOW
			4- OUTPUT_HIGH
*/

/*
 Hint : This is the initial values for the system we could change it using DIO driver
*/
#define PORTA_PIN0_INITIAL_VALUE	OUTPUT_LOW
#define PORTA_PIN1_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN2_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN3_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN4_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN5_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN6_INITIAL_VALUE    OUTPUT_LOW
#define PORTA_PIN7_INITIAL_VALUE	OUTPUT_LOW

#define PORTB_PIN0_INITIAL_VALUE	OUTPUT_LOW
#define PORTB_PIN1_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN2_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN3_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN4_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN5_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN6_INITIAL_VALUE    OUTPUT_LOW
#define PORTB_PIN7_INITIAL_VALUE	OUTPUT_LOW

#define PORTC_PIN0_INITIAL_VALUE	OUTPUT_LOW
#define PORTC_PIN1_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN2_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN3_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN4_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN5_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN6_INITIAL_VALUE    OUTPUT_LOW
#define PORTC_PIN7_INITIAL_VALUE	OUTPUT_LOW

#define PORTD_PIN0_INITIAL_VALUE	OUTPUT_LOW
#define PORTD_PIN1_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN2_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN3_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN4_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN5_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN6_INITIAL_VALUE    OUTPUT_LOW
#define PORTD_PIN7_INITIAL_VALUE	OUTPUT_LOW



#endif /* PORT_CONFIG_H_ */
